import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Gal",
      email: "gal123@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Dan",
      email: "dan@gmail.com",
      password: bcrypt.hashSync("4567", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      imageUrl: "/images/Spinach.jpg",
      name: "Spinach",
      price: "7.50",
      category: "Vegetables",
    },
    {
      _id: "2",
      imageUrl: "/images/Bread.jpg",
      name: "Baget",
      price: "2.00",
      category: "Breads",
    },
    {
      _id: "3",
      imageUrl: "/images/freshly-baked-bread.jpg",
      name: "Freshly Baked Bread",
      price: "3.00",
      category: "Breads",
    },
    {
      _id: "4",
      imageUrl: "/images/Apples.jpg",
      name: "Apple",
      price: "2.00",
      category: "Fruits",
    },
    {
      _id: "5",
      imageUrl: "/images/Avocado.jpg",
      name: "Avocado",
      price: "4.00",
      category: "Vegetables",
    },
    {
      _id: "6",
      imageUrl: "/images/Bagel.jpg",
      name: "Bagel",
      price: "1.00",
      category: "Breads",
    },
    {
      _id: "7",
      imageUrl: "/images/Banana.jpg",
      name: "Banana",
      price: "3.25",
      category: "Fruits",
    },
    {
      _id: "8",
      imageUrl: "/images/Camembert.jpg",
      name: "Camembert",
      price: "4.50",
      category: "Dairy",
    },
    {
      _id: "9",
      imageUrl: "/images/Chia-Seeds.jpg",
      name: "Chia Seeds",
      price: "0.50",
      category: "Spices",
    },
    {
      _id: "10",
      imageUrl: "/images/Cinnamon-Sticks.jpg",
      name: "Cinnamon Sticks",
      price: "0.50",
      category: "Spices",
    },
    {
      _id: "11",
      imageUrl: "/images/Clementine.jpg",
      name: "Clementine",
      price: "2.00",
      category: "Fruits",
    },
    {
      _id: "12",
      imageUrl: "/images/Emmental.jpg",
      name: "Emmental",
      price: "3.50",
      category: "Dairy",
    },
    {
      _id: "13",
      imageUrl: "/images/Grapes.jpg",
      name: "Grapes",
      price: "2.50",
      category: "Fruits",
    },
    {
      _id: "14",
      imageUrl: "/images/Lettuce.jpg",
      name: "Lettuce",
      price: "1.00",
      category: "Vegetables",
    },
    {
      _id: "15",
      imageUrl: "/images/Parmesan.jpg",
      name: "Parmesan",
      price: "3.50",
      category: "Dairy",
    },
    {
      _id: "16",
      imageUrl: "/images/Peach.jpg",
      name: "Peach",
      price: "1.50",
      category: "Fruits",
    },
    {
      _id: "17",
      imageUrl: "/images/Saffron.jpg",
      name: "Saffron",
      price: "3.00",
      category: "Spices",
    },
    {
      _id: "18",
      imageUrl: "/images/Strawberries.jpg",
      name: "Strawberries",
      price: "3.75",
      category: "Fruits",
    },
    {
      _id: "19",
      imageUrl: "/images/Tomato.jpg",
      name: "Tomato",
      price: "2.25",
      category: "Vegetables",
    },
    {
      _id: "20",
      imageUrl: "/images/Turmeric.jpg",
      name: "Turmeric",
      price: "0.75",
      category: "Spices",
    },
    {
      _id: "21",
      imageUrl: "/images/Yellow-Cheese.jpg",
      name: "Yellow Cheese",
      price: "1.25",
      category: "Dairy",
    },
  ],
  Categories: [
    { _id: 1, name: "Bread" },
    { _id: 2, name: "Dairy" },
    { _id: 3, name: "Fruits" },
    { _id: 4, name: "Spices" },
    { _id: 5, name: "Vegetables" },
  ],
};

export default data;
